# Generated by Django 4.2.2 on 2023-06-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=50)),
                ('blog_text', models.CharField(max_length=250)),
                ('blog_link', models.CharField(max_length=250)),
                ('blog_img', models.FilePathField(default='', path='C:\\Users\\Admin\\Desktop\\Portfolio_Django\\My_portf/static/uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_name', models.CharField(max_length=50)),
                ('mail_message', models.CharField(max_length=250)),
                ('mail_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_year', models.CharField(max_length=50)),
                ('edu_tittle', models.CharField(max_length=250)),
                ('edu_about', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_year', models.CharField(max_length=153)),
                ('exp_tittle', models.CharField(max_length=50)),
                ('exp_about', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion_name', models.CharField(max_length=50)),
                ('opinion_text', models.CharField(max_length=150)),
                ('opinion_img', models.FilePathField(default='', path='C:\\Users\\Admin\\Desktop\\Portfolio_Django\\My_portf/static/uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=50)),
                ('portfolio_link', models.CharField(max_length=250)),
                ('portfolio_img', models.FilePathField(default='', path='C:\\Users\\Admin\\Desktop\\Portfolio_Django\\My_portf/static/uploads')),
            ],
        ),
    ]
